redis_server_version: 2.8.10
redis_server_pid_file: /var/run/redis-server.pid
redis_server_conf_file: /etc/redis.conf
redis_server_log_file: /var/log/redis-server.log
redis_server_port: 9736

redis_db_dir: /mnt/redis

gems: [redis]

role_dependencies:
  redis_master: [redis]
  redis_slave: [redis]

roles:
  redis:
    packages: [zip]
    cloud_providers:
      aws:
        image_type: t1.micro
        image_id: ami-0276a81f

security_groups:
  redis:
    description: "To open up port 9736 for http server on web role"
    rules:
      - protocol: tcp
        from_port: "#{redis_server_port}"
        to_port: "#{redis_server_port}"
        source_ips: [0.0.0.0/0]
